name: distributed-process-test-task
version: '0.1.0.0'
category: Web
author: Kamil Figiela
maintainer: kamil.figiela@gmail.com
copyright: 2017 Kamil Figiela
license: BSD3
github: kfigiela/distributed-process-test-task
extra-source-files:
  - README.md
library:
  source-dirs: src
  exposed-modules:
    - Message
    - Collector
    - Broadcaster
    - Broadcaster.API
    - PeerManager
dependencies:
  - base >=4.7 && <5
  - distributed-process
  - distributed-process-simplelocalnet
  - mtl
  - random
  - time
  - binary-orphans
  - lens
  - options
  - containers
  - bytestring
  - network-transport
  - unordered-containers

executables:
  dptt:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - distributed-process-test-task
  dptt-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - distributed-process-test-task
